// crates/wirespec-driver/tests/differential_test.rs
//
// Differential tests: compare C code generated by the Python compiler
// vs the Rust compiler for the same .wspec/.wire input files.
//
// For each example file, we:
// 1. Generate C code using the Rust compiler (programmatic API)
// 2. Generate C code using the Python compiler (subprocess)
// 3. Compare the outputs structurally (not byte-for-byte)

use std::collections::BTreeSet;
use std::fs;
use std::path::PathBuf;
use std::process::Command;
use std::sync::Arc;

use wirespec_backend_api::*;
use wirespec_sema::ComplianceProfile;

fn examples_dir() -> PathBuf {
    PathBuf::from(env!("CARGO_MANIFEST_DIR")).join("../../protospec/examples")
}

fn protospec_dir() -> PathBuf {
    PathBuf::from(env!("CARGO_MANIFEST_DIR")).join("../../protospec")
}

/// Generate C code using the Rust compiler pipeline.
/// Returns (header_content, source_content) on success.
fn generate_c_rust(wspec_path: &str) -> Option<(String, String)> {
    let full_path = examples_dir().join(wspec_path);
    let source = fs::read_to_string(&full_path).ok()?;

    let ast = wirespec_syntax::parse(&source).ok()?;
    let sem =
        wirespec_sema::analyze(&ast, ComplianceProfile::default(), &Default::default()).ok()?;
    let layout = wirespec_layout::lower(&sem).ok()?;
    let codec = wirespec_codec::lower(&layout).ok()?;

    // Derive prefix from module name (same convention as the CLI)
    let prefix = sem.module_name.replace('.', "_");

    let backend = wirespec_backend_c::CBackend;
    let ctx = BackendContext {
        module_name: sem.module_name.clone(),
        module_prefix: prefix,
        source_prefixes: Default::default(),
        compliance_profile: "phase2_extended_current".into(),
        common_options: CommonOptions::default(),
        target_options: Box::new(CBackendOptions::default()),
        checksum_bindings: Arc::new(wirespec_backend_c::checksum_binding::CChecksumBindings),
        is_entry_module: true,
    };
    let lowered = Backend::lower(&backend, &codec, &ctx).ok()?;
    Some((
        lowered.header_content.clone(),
        lowered.source_content.clone(),
    ))
}

/// Generate C code using the Python compiler via subprocess.
/// Returns (header_content, source_content) on success.
fn generate_c_python(wspec_path: &str) -> Option<(String, String)> {
    let full_path = examples_dir().join(wspec_path);
    let tmpdir = tempfile::TempDir::new().ok()?;

    let output = Command::new("python3")
        .args(["-m", "wirespec.cli", "compile"])
        .arg(&full_path)
        .arg("--output")
        .arg(tmpdir.path())
        .arg("--target")
        .arg("c")
        .env("PYTHONPATH", protospec_dir())
        .current_dir(protospec_dir())
        .output()
        .ok()?;

    if !output.status.success() {
        let stderr = String::from_utf8_lossy(&output.stderr);
        eprintln!("  Python compiler failed for {wspec_path}: {stderr}");
        return None;
    }

    // Find generated .h and .c files
    let entries: Vec<_> = fs::read_dir(tmpdir.path())
        .ok()?
        .filter_map(|e| e.ok())
        .collect();

    let h_file = entries
        .iter()
        .find(|e| e.path().extension().is_some_and(|ext| ext == "h"))?;
    let c_file = entries
        .iter()
        .find(|e| e.path().extension().is_some_and(|ext| ext == "c"))?;

    let header = fs::read_to_string(h_file.path()).ok()?;
    let source = fs::read_to_string(c_file.path()).ok()?;
    Some((header, source))
}

/// Extract function declarations from C header content.
/// Looks for lines containing function signatures (parse, serialize, serialized_len).
fn extract_func_decls(header: &str) -> Vec<String> {
    header
        .lines()
        .filter(|line| {
            let trimmed = line.trim();
            (trimmed.contains("wirespec_result_t") || trimmed.contains("size_t"))
                && trimmed.contains("(")
                && !trimmed.starts_with("/*")
                && !trimmed.starts_with("//")
                && !trimmed.starts_with("#")
        })
        .map(|line| line.trim().to_string())
        .collect()
}

/// Extract struct field names from C header content.
/// Returns field names in order, across all structs.
fn extract_struct_fields(header: &str) -> Vec<String> {
    let mut fields = Vec::new();
    let mut in_struct = false;
    for line in header.lines() {
        let trimmed = line.trim();
        if (trimmed.starts_with("struct ") || trimmed.starts_with("typedef struct"))
            && trimmed.ends_with('{')
        {
            in_struct = true;
            continue;
        }
        if in_struct {
            if trimmed == "};" || trimmed.starts_with("} ") {
                in_struct = false;
                continue;
            }
            // Extract field name (last word before ;)
            if let Some(semi) = trimmed.strip_suffix(';') {
                let parts: Vec<&str> = semi.split_whitespace().collect();
                if let Some(name) = parts.last() {
                    // Strip array brackets if present
                    let name = name.split('[').next().unwrap_or(name);
                    let name = name.trim_start_matches('*');
                    if !name.is_empty() && name != "{" {
                        fields.push(name.to_string());
                    }
                }
            }
        }
    }
    fields
}

/// Extract struct/union type names from C header content.
fn extract_type_names(header: &str) -> BTreeSet<String> {
    let mut types = BTreeSet::new();
    for line in header.lines() {
        let trimmed = line.trim();
        // "typedef struct foo_bar foo_bar_t;" pattern
        if trimmed.starts_with("typedef struct ") || trimmed.starts_with("typedef union ") {
            if let Some(name) = trimmed.split_whitespace().nth(2) {
                // Filter out "{" which appears when the typedef spans multiple lines
                if name != "{" && !name.is_empty() {
                    types.insert(name.to_string());
                }
            }
        }
        // Also look for "struct foo_bar {" pattern
        if trimmed.starts_with("struct ") && trimmed.ends_with('{') {
            if let Some(name) = trimmed
                .strip_prefix("struct ")
                .and_then(|s| s.strip_suffix(" {"))
            {
                types.insert(name.to_string());
            }
        }
    }
    types
}

/// Compare outputs from both compilers for a given .wire file.
fn compare_outputs(name: &str, wspec_path: &str) {
    eprintln!("\n=== Differential test: {name} ({wspec_path}) ===");

    let rust_result = generate_c_rust(wspec_path);
    let python_result = generate_c_python(wspec_path);

    match (rust_result, python_result) {
        (Some((rust_h, rust_c)), Some((python_h, python_c))) => {
            eprintln!("  Both compilers succeeded.");

            // -- Type names --
            let rust_types = extract_type_names(&rust_h);
            let python_types = extract_type_names(&python_h);

            eprintln!("  Rust types:   {:?}", rust_types);
            eprintln!("  Python types: {:?}", python_types);

            let common_types: BTreeSet<_> = rust_types.intersection(&python_types).collect();
            let rust_only_types: BTreeSet<_> = rust_types.difference(&python_types).collect();
            let python_only_types: BTreeSet<_> = python_types.difference(&rust_types).collect();

            if !rust_only_types.is_empty() {
                eprintln!("  Types only in Rust:   {:?}", rust_only_types);
            }
            if !python_only_types.is_empty() {
                eprintln!("  Types only in Python: {:?}", python_only_types);
            }
            eprintln!(
                "  Common types: {} of {}",
                common_types.len(),
                rust_types.len().max(python_types.len())
            );

            // -- Function declarations --
            let rust_funcs = extract_func_decls(&rust_h);
            let python_funcs = extract_func_decls(&python_h);

            eprintln!("  Rust function decls:   {}", rust_funcs.len());
            eprintln!("  Python function decls: {}", python_funcs.len());

            if rust_funcs.len() != python_funcs.len() {
                eprintln!("  WARNING: Function count mismatch");
                eprintln!("    Rust functions:");
                for f in &rust_funcs {
                    eprintln!("      {f}");
                }
                eprintln!("    Python functions:");
                for f in &python_funcs {
                    eprintln!("      {f}");
                }
            }

            // -- Struct fields --
            let rust_fields = extract_struct_fields(&rust_h);
            let python_fields = extract_struct_fields(&python_h);

            eprintln!("  Rust struct fields:   {:?}", rust_fields);
            eprintln!("  Python struct fields: {:?}", python_fields);

            let rust_field_set: BTreeSet<_> = rust_fields.iter().collect();
            let python_field_set: BTreeSet<_> = python_fields.iter().collect();
            let matching = rust_field_set.intersection(&python_field_set).count();
            let total = rust_field_set.len().max(python_field_set.len());
            eprintln!("  Field name overlap: {matching}/{total}");

            let rust_only: Vec<_> = rust_field_set.difference(&python_field_set).collect();
            let python_only: Vec<_> = python_field_set.difference(&rust_field_set).collect();

            if !rust_only.is_empty() {
                eprintln!("  Rust-only fields: {:?}", rust_only);
            }
            if !python_only.is_empty() {
                eprintln!("  Python-only fields: {:?}", python_only);
            }

            // -- Size comparison --
            eprintln!(
                "  Header size: Rust={} bytes, Python={} bytes",
                rust_h.len(),
                python_h.len()
            );
            eprintln!(
                "  Source size: Rust={} bytes, Python={} bytes",
                rust_c.len(),
                python_c.len()
            );

            // Assertions: both should produce non-empty output
            assert!(!rust_h.is_empty(), "Rust header is empty for {wspec_path}");
            assert!(!rust_c.is_empty(), "Rust source is empty for {wspec_path}");
            assert!(
                !python_h.is_empty(),
                "Python header is empty for {wspec_path}"
            );
            assert!(
                !python_c.is_empty(),
                "Python source is empty for {wspec_path}"
            );
        }
        (Some(_), None) => {
            eprintln!(
                "  SKIP: Python compiler failed (may not be installed or file not supported)"
            );
        }
        (None, Some(_)) => {
            eprintln!("  FAIL: Rust compiler failed but Python succeeded");
            panic!("Rust compiler failed for {wspec_path}");
        }
        (None, None) => {
            eprintln!("  SKIP: Both compilers failed for {wspec_path}");
        }
    }
}

#[test]
fn differential_udp() {
    compare_outputs("UDP", "net/udp.wire");
}

#[test]
fn differential_tcp() {
    compare_outputs("TCP", "net/tcp.wire");
}

#[test]
fn differential_ethernet() {
    compare_outputs("Ethernet", "net/ethernet.wire");
}

#[test]
fn differential_varint() {
    compare_outputs("QUIC VarInt", "quic/varint.wire");
}

#[test]
fn differential_bits_groups() {
    compare_outputs("Bits Groups", "test/bits_groups.wire");
}

#[test]
fn differential_ble_att() {
    compare_outputs("BLE ATT", "ble/att.wire");
}

#[test]
fn differential_mqtt() {
    compare_outputs("MQTT", "mqtt/mqtt.wire");
}
