// crates/wirespec-backend-rust/src/emit.rs
//
// Full .rs file emission: structs, enums, impl blocks, frames, capsules,
// varints, state machines.

use crate::names::*;
use crate::parse_emit;
use crate::serialize_emit;
use crate::type_map::*;
use wirespec_codec::ir::*;
use wirespec_sema::expr::{SemanticExpr, SemanticLiteral, TransitionPeerKind};
use wirespec_sema::ir::*;

const MAX_ARRAY_ELEMENTS: u32 = 256;

/// Check if any field in a list uses bytes (needs lifetime `<'a>`).
fn fields_need_lifetime(fields: &[CodecField]) -> bool {
    for f in fields {
        match f.strategy {
            FieldStrategy::BytesFixed
            | FieldStrategy::BytesLength
            | FieldStrategy::BytesRemaining
            | FieldStrategy::BytesLor => return true,
            FieldStrategy::Conditional => {
                let inner = f.inner_wire_type.as_ref().unwrap_or(&f.wire_type);
                if matches!(inner, WireType::Bytes) {
                    return true;
                }
                if wire_type_is_named(inner) {
                    // Conservatively assume named types in conditionals may have lifetime
                    return true;
                }
            }
            FieldStrategy::Struct => {
                // Named struct types might have lifetimes; conservative
                return true;
            }
            _ => {}
        }
    }
    false
}

/// Check if a packet needs lifetime.
fn packet_needs_lifetime(packet: &CodecPacket) -> bool {
    fields_need_lifetime(&packet.fields)
}

/// Check if a frame needs lifetime.
fn frame_needs_lifetime(frame: &CodecFrame) -> bool {
    for variant in &frame.variants {
        if fields_need_lifetime(&variant.fields) {
            return true;
        }
    }
    false
}

/// Check if a capsule needs lifetime.
fn capsule_needs_lifetime(capsule: &CodecCapsule) -> bool {
    if fields_need_lifetime(&capsule.header_fields) {
        return true;
    }
    for variant in &capsule.variants {
        if fields_need_lifetime(&variant.fields) {
            return true;
        }
    }
    false
}

/// Lifetime suffix: `<'a>` if needed, empty otherwise.
fn lifetime_suffix(needs: bool) -> &'static str {
    if needs { "<'a>" } else { "" }
}

/// Emit the complete .rs source file content.
pub fn emit_source(module: &CodecModule, _prefix: &str) -> String {
    let mut out = String::new();

    // Header
    out.push_str("// Auto-generated by wirespec. Do not edit.\n");
    out.push_str("#![allow(unused_imports, unused_variables, dead_code, unused_mut, unused_parens, unreachable_patterns)]\n\n");
    out.push_str("use wirespec_rt::*;\n\n");

    // VarInts
    for vi in &module.varints {
        emit_varint(&mut out, vi);
    }

    // Constants
    for c in &module.consts {
        emit_const(&mut out, c);
    }
    if !module.consts.is_empty() {
        out.push('\n');
    }

    // Enums (as type alias + pub const values)
    for e in &module.enums {
        emit_enum(&mut out, e);
    }

    // Packets
    for packet in &module.packets {
        emit_packet(&mut out, packet);
    }

    // Frames
    for frame in &module.frames {
        emit_frame(&mut out, frame);
    }

    // Capsules
    for capsule in &module.capsules {
        emit_capsule(&mut out, capsule);
    }

    // State Machines
    for sm in &module.state_machines {
        emit_state_machine(&mut out, sm);
    }

    out
}

// ── Constants ──

fn emit_const(out: &mut String, c: &wirespec_sema::ir::SemanticConst) {
    let name = c.name.to_uppercase();
    let ty = semantic_type_to_rust(&c.ty);
    let val = semantic_literal_to_rust(&c.value);
    out.push_str(&format!("pub const {name}: {ty} = {val};\n"));
}

fn semantic_type_to_rust(ty: &wirespec_sema::types::SemanticType) -> &'static str {
    match ty {
        wirespec_sema::types::SemanticType::Primitive { wire, .. } => match wire {
            wirespec_sema::types::PrimitiveWireType::U8 => "u8",
            wirespec_sema::types::PrimitiveWireType::U16 => "u16",
            wirespec_sema::types::PrimitiveWireType::U24 => "u32",
            wirespec_sema::types::PrimitiveWireType::U32 => "u32",
            wirespec_sema::types::PrimitiveWireType::U64 => "u64",
            wirespec_sema::types::PrimitiveWireType::I8 => "i8",
            wirespec_sema::types::PrimitiveWireType::I16 => "i16",
            wirespec_sema::types::PrimitiveWireType::I32 => "i32",
            wirespec_sema::types::PrimitiveWireType::I64 => "i64",
            wirespec_sema::types::PrimitiveWireType::Bool => "bool",
            wirespec_sema::types::PrimitiveWireType::Bit => "u8",
        },
        wirespec_sema::types::SemanticType::Bits { width_bits } => {
            if *width_bits <= 8 {
                "u8"
            } else if *width_bits <= 16 {
                "u16"
            } else if *width_bits <= 32 {
                "u32"
            } else {
                "u64"
            }
        }
        _ => "u64",
    }
}

fn semantic_literal_to_rust(lit: &wirespec_sema::expr::SemanticLiteral) -> String {
    match lit {
        wirespec_sema::expr::SemanticLiteral::Int(n) => format!("{n}"),
        wirespec_sema::expr::SemanticLiteral::Bool(b) => format!("{b}"),
        wirespec_sema::expr::SemanticLiteral::String(s) => format!("{s:?}"),
        wirespec_sema::expr::SemanticLiteral::Null => "0".into(),
    }
}

// ── Enums ──

fn emit_enum(out: &mut String, e: &wirespec_sema::ir::SemanticEnum) {
    let base_type = semantic_type_to_rust(&e.underlying_type);
    let type_name = to_pascal_case(&e.name);
    // Type alias for the enum
    out.push_str(&format!("pub type {type_name} = {base_type};\n"));
    for member in &e.members {
        let const_name = format!(
            "{}_{}",
            to_snake_case(&e.name).to_uppercase(),
            to_snake_case(&member.name).to_uppercase()
        );
        out.push_str(&format!(
            "pub const {const_name}: {type_name} = {};\n",
            member.value
        ));
    }
    out.push('\n');
}

// ── Packets ──

fn emit_packet(out: &mut String, packet: &CodecPacket) {
    let type_name = to_pascal_case(&packet.name);
    let needs_lt = packet_needs_lifetime(packet);
    let lt = lifetime_suffix(needs_lt);

    let has_cksum = packet.checksum_plan.is_some();
    // Parse needs offset tracking for recompute-compare algorithms (CRC, fletcher)
    let parse_needs_offset = has_cksum
        && packet.checksum_plan.as_ref().map_or(false, |p| {
            p.input_model == ChecksumInputModel::RecomputeWithSkippedField
        });
    // Serialize always needs offset tracking when checksum is present (all algorithms need it)

    // Struct definition
    out.push_str("#[derive(Debug, Clone, PartialEq)]\n");
    out.push_str(&format!("pub struct {type_name}{lt} {{\n"));
    emit_struct_fields(out, &packet.fields, &packet.items);
    out.push_str("}\n\n");

    // Impl block
    out.push_str(&format!("impl{lt} {type_name}{lt} {{\n"));

    // parse method
    out.push_str(&format!(
        "    pub fn parse(cur: &mut Cursor{}) -> Result<Self> {{\n",
        if needs_lt { "<'a>" } else { "<'_>" }
    ));

    // Record start position for checksum verification
    if has_cksum {
        out.push_str("        let _start = cur.consumed();\n");
    }
    if parse_needs_offset {
        out.push_str("        let mut _cksum_offset: usize = 0;\n");
    }

    // Emit parse items, tracking checksum field offset if needed
    if parse_needs_offset {
        let cksum_plan = packet.checksum_plan.as_ref().unwrap();
        emit_parse_items_with_cksum_tracking(
            out,
            &packet.fields,
            &packet.items,
            "        ",
            &cksum_plan.field_name,
        );
    } else {
        parse_emit::emit_parse_items(out, &packet.fields, &packet.items, "        ");
    }

    // Checksum verify after parse, before returning
    if let Some(ref plan) = packet.checksum_plan {
        emit_checksum_verify_rust(out, plan, "        ");
    }

    // Return Ok(Self { ... })
    out.push_str("        Ok(Self {\n");
    emit_struct_init_fields(out, &packet.fields, &packet.items, "            ");
    out.push_str("        })\n");
    out.push_str("    }\n\n");

    // serialize method
    out.push_str("    pub fn serialize(&self, w: &mut Writer<'_>) -> Result<()> {\n");

    if has_cksum {
        out.push_str("        let _start = w.written();\n");
        out.push_str("        let mut _cksum_offset: usize = 0;\n");
        let cksum_plan = packet.checksum_plan.as_ref().unwrap();
        emit_serialize_items_with_cksum_tracking(
            out,
            &packet.fields,
            &packet.items,
            "        ",
            "self.",
            &cksum_plan.field_name,
        );
    } else {
        serialize_emit::emit_serialize_items(
            out,
            &packet.fields,
            &packet.items,
            "        ",
            "self.",
        );
    }

    // Checksum compute after all fields written
    if let Some(ref plan) = packet.checksum_plan {
        emit_checksum_compute_rust(out, plan, "        ");
    }

    out.push_str("        Ok(())\n");
    out.push_str("    }\n\n");

    // serialized_len method
    out.push_str("    pub fn serialized_len(&self) -> usize {\n");
    out.push_str("        let mut len = 0usize;\n");
    serialize_emit::emit_serialized_len_items(
        out,
        &packet.fields,
        &packet.items,
        "        ",
        "self.",
    );
    out.push_str("        len\n");
    out.push_str("    }\n");

    out.push_str("}\n\n");
}

/// Emit parse items while tracking the byte offset of the checksum field.
fn emit_parse_items_with_cksum_tracking(
    out: &mut String,
    fields: &[CodecField],
    items: &[CodecItem],
    indent: &str,
    cksum_field_name: &str,
) {
    for item in items {
        if let CodecItem::Field { field_id } = item {
            if let Some(f) = fields.iter().find(|f| &f.field_id == field_id) {
                if f.name == cksum_field_name {
                    out.push_str(&format!(
                        "{indent}_cksum_offset = cur.consumed() - _start;\n"
                    ));
                }
            }
        }
        let single_items = [item.clone()];
        parse_emit::emit_parse_items(out, fields, &single_items, indent);
    }
}

/// Emit serialize items while tracking the byte offset of the checksum field.
fn emit_serialize_items_with_cksum_tracking(
    out: &mut String,
    fields: &[CodecField],
    items: &[CodecItem],
    indent: &str,
    val_prefix: &str,
    cksum_field_name: &str,
) {
    for item in items {
        if let CodecItem::Field { field_id } = item {
            if let Some(f) = fields.iter().find(|f| &f.field_id == field_id) {
                if f.name == cksum_field_name {
                    out.push_str(&format!("{indent}_cksum_offset = w.written() - _start;\n"));
                }
            }
        }
        let single_items = [item.clone()];
        serialize_emit::emit_serialize_items(out, fields, &single_items, indent, val_prefix);
    }
}

/// Emit checksum verification code after parse.
fn emit_checksum_verify_rust(out: &mut String, plan: &ChecksumPlan, indent: &str) {
    use wirespec_sema::checksum_catalog;

    let algo = &plan.algorithm_id;
    let spec = checksum_catalog::lookup(algo);

    match spec.map(|s| s.verify_mode) {
        Some(checksum_catalog::ChecksumVerifyMode::ZeroSum) => {
            // Zero-sum verify: sum of entire scope including checksum field == 0
            out.push_str(&format!("{indent}{{\n"));
            out.push_str(&format!(
                "{indent}    let _cksum = {algo}_checksum(&cur.bytes()[_start..cur.consumed()]);\n"
            ));
            out.push_str(&format!(
                "{indent}    if _cksum != 0 {{ return Err(Error::Checksum); }}\n"
            ));
            out.push_str(&format!("{indent}}}\n"));
        }
        Some(checksum_catalog::ChecksumVerifyMode::RecomputeCompare) => {
            // Recompute skipping the checksum field, compare
            let width = plan.field_width_bytes;
            out.push_str(&format!("{indent}{{\n"));
            out.push_str(&format!(
                "{indent}    let _scope = &cur.bytes()[_start..cur.consumed()];\n"
            ));
            out.push_str(&format!(
                "{indent}    let _computed = {algo}_verify(_scope, _cksum_offset, {width});\n"
            ));
            out.push_str(&format!(
                "{indent}    if {field} != _computed {{ return Err(Error::Checksum); }}\n",
                field = plan.field_name,
            ));
            out.push_str(&format!("{indent}}}\n"));
        }
        None => {
            out.push_str(&format!(
                "{indent}// TODO: unsupported checksum algorithm '{algo}'\n"
            ));
        }
    }
}

/// Emit checksum compute code after serialize.
fn emit_checksum_compute_rust(out: &mut String, plan: &ChecksumPlan, indent: &str) {
    use wirespec_sema::checksum_catalog;

    let algo = &plan.algorithm_id;
    let spec = checksum_catalog::lookup(algo);

    out.push_str(&format!("{indent}// Checksum compute ({algo})\n"));

    match spec.map(|s| s.verify_mode) {
        Some(checksum_catalog::ChecksumVerifyMode::ZeroSum) => {
            // Zero-sum compute: patch-in-place
            out.push_str(&format!("{indent}{{\n"));
            out.push_str(&format!("{indent}    let _written = w.as_written_mut();\n"));
            out.push_str(&format!(
                "{indent}    {algo}_checksum_compute(&mut _written[_start..], _cksum_offset);\n"
            ));
            out.push_str(&format!("{indent}}}\n"));
        }
        Some(checksum_catalog::ChecksumVerifyMode::RecomputeCompare) => {
            // Recompute: compute value, write bytes big-endian
            let width = plan.field_width_bytes;
            out.push_str(&format!("{indent}{{\n"));
            out.push_str(&format!("{indent}    let _end = w.written();\n"));
            out.push_str(&format!("{indent}    let _written = w.as_written_mut();\n"));
            out.push_str(&format!(
                "{indent}    let _val = {algo}_compute(&mut _written[_start.._end], _cksum_offset);\n"
            ));
            for i in 0..width {
                let shift = (width - 1 - i) * 8;
                out.push_str(&format!(
                    "{indent}    _written[_start + _cksum_offset + {i}] = ((_val >> {shift}) & 0xFF) as u8;\n"
                ));
            }
            out.push_str(&format!("{indent}}}\n"));
        }
        None => {
            out.push_str(&format!(
                "{indent}// TODO: unsupported checksum algorithm '{algo}'\n"
            ));
        }
    }
}

// ── Frames ──

fn emit_frame(out: &mut String, frame: &CodecFrame) {
    let type_name = to_pascal_case(&frame.name);
    let needs_lt = frame_needs_lifetime(frame);
    let lt = lifetime_suffix(needs_lt);
    let tag_type = wire_type_to_rust(&frame.tag.wire_type);

    // Enum definition
    out.push_str("#[derive(Debug, Clone, PartialEq)]\n");
    out.push_str(&format!("pub enum {type_name}{lt} {{\n"));
    for variant in &frame.variants {
        let variant_name = to_pascal_case(&variant.name);
        if variant.fields.is_empty()
            && !variant
                .items
                .iter()
                .any(|i| matches!(i, CodecItem::Derived(_)))
        {
            out.push_str(&format!("    {variant_name},\n"));
        } else {
            out.push_str(&format!("    {variant_name} {{\n"));
            emit_variant_struct_fields(out, variant);
            out.push_str("    },\n");
        }
    }
    out.push_str("}\n\n");

    // Impl block
    out.push_str(&format!("impl{lt} {type_name}{lt} {{\n"));

    // parse method — returns (Self, tag_type)
    out.push_str(&format!(
        "    pub fn parse(cur: &mut Cursor{}) -> Result<(Self, {tag_type})> {{\n",
        if needs_lt { "<'a>" } else { "<'_>" }
    ));
    parse_emit::emit_frame_parse_body(out, frame, "        ");
    out.push_str("    }\n\n");

    // serialize method — tag is passed in
    out.push_str(&format!(
        "    pub fn serialize(&self, tag: {tag_type}, w: &mut Writer<'_>) -> Result<()> {{\n"
    ));
    serialize_emit::emit_frame_serialize_body(out, frame, "        ");
    out.push_str("        Ok(())\n");
    out.push_str("    }\n\n");

    // serialized_len method
    out.push_str("    pub fn serialized_len(&self) -> usize {\n");
    out.push_str("        let mut len = 0usize;\n");
    serialize_emit::emit_frame_serialized_len_body(out, frame, "        ");
    out.push_str("        len\n");
    out.push_str("    }\n");

    out.push_str("}\n\n");
}

// ── Capsules ──

fn emit_capsule(out: &mut String, capsule: &CodecCapsule) {
    let type_name = to_pascal_case(&capsule.name);
    let needs_lt = capsule_needs_lifetime(capsule);
    let lt = lifetime_suffix(needs_lt);

    // Struct definition (header fields + payload enum)
    out.push_str("#[derive(Debug, Clone, PartialEq)]\n");
    out.push_str(&format!("pub struct {type_name}{lt} {{\n"));
    // Header fields
    emit_struct_fields(out, &capsule.header_fields, &capsule.header_items);
    // Payload as an enum
    out.push_str(&format!("    pub payload: {type_name}Payload{lt},\n"));
    out.push_str("}\n\n");

    // Payload enum
    out.push_str("#[derive(Debug, Clone, PartialEq)]\n");
    out.push_str(&format!("pub enum {type_name}Payload{lt} {{\n"));
    for variant in &capsule.variants {
        let variant_name = to_pascal_case(&variant.name);
        if variant.fields.is_empty() {
            out.push_str(&format!("    {variant_name},\n"));
        } else {
            out.push_str(&format!("    {variant_name} {{\n"));
            emit_variant_struct_fields(out, variant);
            out.push_str("    },\n");
        }
    }
    out.push_str("}\n\n");

    // Impl block
    out.push_str(&format!("impl{lt} {type_name}{lt} {{\n"));

    // parse method
    out.push_str(&format!(
        "    pub fn parse(cur: &mut Cursor{}) -> Result<Self> {{\n",
        if needs_lt { "<'a>" } else { "<'_>" }
    ));
    parse_emit::emit_capsule_parse_body(out, capsule, "        ");
    out.push_str("    }\n\n");

    // serialize method
    out.push_str("    pub fn serialize(&self, w: &mut Writer<'_>) -> Result<()> {\n");
    serialize_emit::emit_serialize_items(
        out,
        &capsule.header_fields,
        &capsule.header_items,
        "        ",
        "self.",
    );
    out.push_str("        Ok(())\n");
    out.push_str("    }\n\n");

    // serialized_len method
    out.push_str("    pub fn serialized_len(&self) -> usize {\n");
    out.push_str("        let mut len = 0usize;\n");
    serialize_emit::emit_serialized_len_items(
        out,
        &capsule.header_fields,
        &capsule.header_items,
        "        ",
        "self.",
    );
    out.push_str("        len\n");
    out.push_str("    }\n");

    out.push_str("}\n\n");
}

// ── Shared helpers ──

/// Emit struct fields for packets and capsule headers.
fn emit_struct_fields(out: &mut String, fields: &[CodecField], items: &[CodecItem]) {
    for item in items {
        match item {
            CodecItem::Field { field_id } => {
                if let Some(f) = fields.iter().find(|f| &f.field_id == field_id) {
                    emit_single_struct_field(out, f);
                }
            }
            CodecItem::Derived(d) => {
                let ty = wire_type_to_rust(&d.wire_type);
                out.push_str(&format!("    pub {}: {ty},\n", d.name));
            }
            CodecItem::Require(_) => {}
        }
    }
}

fn emit_single_struct_field(out: &mut String, f: &CodecField) {
    match f.strategy {
        FieldStrategy::BitGroup => {
            let ty = wire_type_to_rust(&f.wire_type);
            out.push_str(&format!("    pub {}: {ty},\n", f.name));
        }
        FieldStrategy::Conditional => {
            let inner_wt = f.inner_wire_type.as_ref().unwrap_or(&f.wire_type);
            let inner_ty = rust_field_type(inner_wt);
            out.push_str(&format!("    pub {}: Option<{inner_ty}>,\n", f.name));
        }
        FieldStrategy::Array => {
            if let Some(ref arr) = f.array_spec {
                let elem_ty = rust_field_type(&arr.element_wire_type);
                let max_elems = f.max_elements.unwrap_or(MAX_ARRAY_ELEMENTS);
                out.push_str(&format!("    pub {}: [{elem_ty}; {max_elems}],\n", f.name));
                out.push_str(&format!("    pub {}_count: usize,\n", f.name));
            }
        }
        FieldStrategy::BytesFixed
        | FieldStrategy::BytesLength
        | FieldStrategy::BytesRemaining
        | FieldStrategy::BytesLor => {
            out.push_str(&format!("    pub {}: &'a [u8],\n", f.name));
        }
        FieldStrategy::Struct => {
            if let Some(ref ref_name) = f.ref_type_name {
                let type_name = to_pascal_case(ref_name);
                // TODO: track whether the inner struct needs lifetime
                out.push_str(&format!("    pub {}: {type_name},\n", f.name));
            } else {
                let ty = wire_type_to_rust(&f.wire_type);
                out.push_str(&format!("    pub {}: {ty},\n", f.name));
            }
        }
        FieldStrategy::VarInt | FieldStrategy::ContVarInt => {
            out.push_str(&format!("    pub {}: u64,\n", f.name));
        }
        _ => {
            // Primitive / Checksum
            let ty = wire_type_to_rust(&f.wire_type);
            out.push_str(&format!("    pub {}: {ty},\n", f.name));
        }
    }
}

/// Get the Rust field type string for a wire type.
fn rust_field_type(wt: &WireType) -> String {
    match wt {
        WireType::Bytes => "&'a [u8]".into(),
        WireType::Struct(name) | WireType::Frame(name) | WireType::Capsule(name) => {
            to_pascal_case(name)
        }
        WireType::Enum(name) => {
            // Enums are represented as their underlying type in Rust (pub const pattern)
            // We need to look at the enum to know the type; for now use the wire type
            to_pascal_case(name)
        }
        _ => wire_type_to_rust(wt).to_string(),
    }
}

/// Emit the field initializers for Ok(Self { ... }) construction.
fn emit_struct_init_fields(
    out: &mut String,
    fields: &[CodecField],
    items: &[CodecItem],
    indent: &str,
) {
    for item in items {
        match item {
            CodecItem::Field { field_id } => {
                if let Some(f) = fields.iter().find(|f| &f.field_id == field_id) {
                    out.push_str(&format!("{indent}{},\n", f.name));
                    if f.strategy == FieldStrategy::Array {
                        out.push_str(&format!("{indent}{}_count,\n", f.name));
                    }
                }
            }
            CodecItem::Derived(d) => {
                out.push_str(&format!("{indent}{},\n", d.name));
            }
            CodecItem::Require(_) => {}
        }
    }
}

/// Emit struct fields for frame/capsule variant inner fields.
fn emit_variant_struct_fields(out: &mut String, variant: &CodecVariantScope) {
    for item in &variant.items {
        match item {
            CodecItem::Field { field_id } => {
                if let Some(f) = variant.fields.iter().find(|f| &f.field_id == field_id) {
                    emit_variant_single_field(out, f);
                }
            }
            CodecItem::Derived(d) => {
                let ty = wire_type_to_rust(&d.wire_type);
                out.push_str(&format!("        {}: {ty},\n", d.name));
            }
            CodecItem::Require(_) => {}
        }
    }
}

fn emit_variant_single_field(out: &mut String, f: &CodecField) {
    match f.strategy {
        FieldStrategy::Conditional => {
            let inner_wt = f.inner_wire_type.as_ref().unwrap_or(&f.wire_type);
            let inner_ty = rust_field_type(inner_wt);
            out.push_str(&format!("        {}: Option<{inner_ty}>,\n", f.name));
        }
        FieldStrategy::Array => {
            if let Some(ref arr) = f.array_spec {
                let elem_ty = rust_field_type(&arr.element_wire_type);
                let max_elems = f.max_elements.unwrap_or(MAX_ARRAY_ELEMENTS);
                out.push_str(&format!("        {}: [{elem_ty}; {max_elems}],\n", f.name));
                out.push_str(&format!("        {}_count: usize,\n", f.name));
            }
        }
        FieldStrategy::BytesFixed
        | FieldStrategy::BytesLength
        | FieldStrategy::BytesRemaining
        | FieldStrategy::BytesLor => {
            out.push_str(&format!("        {}: &'a [u8],\n", f.name));
        }
        FieldStrategy::Struct => {
            if let Some(ref ref_name) = f.ref_type_name {
                let type_name = to_pascal_case(ref_name);
                out.push_str(&format!("        {}: {type_name},\n", f.name));
            } else {
                let ty = wire_type_to_rust(&f.wire_type);
                out.push_str(&format!("        {}: {ty},\n", f.name));
            }
        }
        FieldStrategy::VarInt | FieldStrategy::ContVarInt => {
            out.push_str(&format!("        {}: u64,\n", f.name));
        }
        _ => {
            let ty = wire_type_to_rust(&f.wire_type);
            out.push_str(&format!("        {}: {ty},\n", f.name));
        }
    }
}

// ── VarInts ──

fn emit_varint(out: &mut String, vi: &SemanticVarInt) {
    let snake = to_snake_case(&vi.name);

    match vi.encoding {
        VarIntEncoding::PrefixMatch => emit_varint_prefix_match(out, vi, &snake),
        VarIntEncoding::ContinuationBit => emit_varint_continuation_bit(out, vi, &snake),
    }
}

fn emit_varint_prefix_match(out: &mut String, vi: &SemanticVarInt, snake: &str) {
    let prefix_bits = vi.prefix_bits.unwrap_or(2) as u32;

    // ── parse ──
    out.push_str(&format!(
        "pub fn {snake}_parse(cur: &mut Cursor<'_>) -> Result<u64> {{\n"
    ));
    out.push_str("    let first = cur.read_u8()?;\n");
    out.push_str(&format!("    let prefix = first >> {};\n", 8 - prefix_bits));
    if vi.strict && vi.branches.len() > 1 {
        // @strict: capture val from match so we can validate after
        out.push_str("    let val = match prefix {\n");
    } else {
        out.push_str("    match prefix {\n");
    }

    for branch in &vi.branches {
        let pv = branch.prefix_value;
        let total_bytes = branch.total_bytes as u32;
        let value_bits_first = 8 - prefix_bits as u8;
        let value_mask_first: u8 = (1u16 << value_bits_first) as u8 - 1;

        out.push_str(&format!("        {pv} => {{\n"));

        if total_bytes == 1 {
            out.push_str(&format!(
                "            let val = (first & 0x{value_mask_first:02x}) as u64;\n"
            ));
        } else {
            out.push_str(&format!(
                "            let mut val = ((first & 0x{value_mask_first:02x}) as u64) << {};\n",
                (total_bytes - 1) * 8
            ));
            for i in 1..total_bytes {
                out.push_str(&format!(
                    "            val |= (cur.read_u8()? as u64) << {};\n",
                    (total_bytes - 1 - i) * 8
                ));
            }
        }

        if vi.strict && vi.branches.len() > 1 {
            out.push_str("            val\n");
        } else {
            out.push_str("            Ok(val)\n");
        }
        out.push_str("        }\n");
    }

    if vi.strict && vi.branches.len() > 1 {
        out.push_str("        _ => { return Err(Error::InvalidTag); }\n");
        out.push_str("    };\n");
        // @strict: reject non-canonical encodings
        out.push_str("    // @strict: reject non-canonical encodings\n");
        for i in 1..vi.branches.len() {
            let prev_max = vi.branches[i - 1].max_value;
            let prefix_val = vi.branches[i].prefix_value;
            out.push_str(&format!(
                "    if prefix == {} && val <= {} {{ return Err(Error::Noncanonical); }}\n",
                prefix_val, prev_max
            ));
        }
        out.push_str("    Ok(val)\n");
    } else {
        out.push_str("        _ => Err(Error::InvalidTag),\n");
        out.push_str("    }\n");
    }

    out.push_str("}\n\n");

    // ── serialize ──
    out.push_str(&format!(
        "pub fn {snake}_serialize(val: u64, w: &mut Writer<'_>) -> Result<()> {{\n"
    ));

    for (i, branch) in vi.branches.iter().enumerate() {
        let max_val = branch.max_value;
        let total_bytes = branch.total_bytes as u32;
        let prefix_byte = (branch.prefix_value as u8) << (8 - prefix_bits);

        let cond = if i == 0 {
            format!("    if val <= {max_val}")
        } else {
            format!("    }} else if val <= {max_val}")
        };

        out.push_str(&format!("{cond} {{\n"));

        if total_bytes == 1 {
            out.push_str(&format!(
                "        w.write_u8(0x{prefix_byte:02x} | (val as u8))?;\n"
            ));
        } else {
            out.push_str(&format!(
                "        w.write_u8(0x{prefix_byte:02x} | ((val >> {}) as u8))?;\n",
                (total_bytes - 1) * 8
            ));
            for j in 1..total_bytes {
                let shift = (total_bytes - 1 - j) * 8;
                if shift == 0 {
                    out.push_str("        w.write_u8(val as u8)?;\n");
                } else {
                    out.push_str(&format!("        w.write_u8((val >> {shift}) as u8)?;\n"));
                }
            }
        }
    }

    if !vi.branches.is_empty() {
        out.push_str("    } else {\n");
        out.push_str("        return Err(Error::Overflow);\n");
        out.push_str("    }\n");
    }

    out.push_str("    Ok(())\n");
    out.push_str("}\n\n");

    // ── wire_size ──
    out.push_str(&format!("pub fn {snake}_wire_size(val: u64) -> usize {{\n"));

    for (i, branch) in vi.branches.iter().enumerate() {
        let max_val = branch.max_value;
        let total_bytes = branch.total_bytes;

        if i == 0 {
            out.push_str(&format!("    if val <= {max_val} {{ {total_bytes} }}\n"));
        } else {
            out.push_str(&format!(
                "    else if val <= {max_val} {{ {total_bytes} }}\n"
            ));
        }
    }

    out.push_str(&format!("    else {{ {} }}\n", vi.max_bytes));
    out.push_str("}\n\n");
}

fn emit_varint_continuation_bit(out: &mut String, vi: &SemanticVarInt, snake: &str) {
    let value_bits = vi.value_bits_per_byte.unwrap_or(7) as u32;
    let max_bytes = vi.max_bytes;
    let value_mask: u8 = (1u16 << value_bits) as u8 - 1;
    let cont_mask: u8 = !value_mask;

    // ── parse ──
    out.push_str(&format!(
        "pub fn {snake}_parse(cur: &mut Cursor<'_>) -> Result<u64> {{\n"
    ));
    out.push_str("    let mut value: u64 = 0;\n");
    out.push_str("    let mut shift: u32 = 0;\n");
    out.push_str(&format!("    for _ in 0..{max_bytes} {{\n"));
    out.push_str("        let byte = cur.read_u8()?;\n");
    out.push_str(&format!(
        "        let chunk = (byte & 0x{value_mask:02x}) as u64;\n"
    ));
    out.push_str("        value |= chunk << shift;\n");
    out.push_str(&format!(
        "        if (byte & 0x{cont_mask:02x}) == 0 {{ return Ok(value); }}\n"
    ));
    out.push_str(&format!("        shift += {value_bits};\n"));
    out.push_str("    }\n");
    out.push_str("    Err(Error::Overflow)\n");
    out.push_str("}\n\n");

    // ── serialize ──
    out.push_str(&format!(
        "pub fn {snake}_serialize(mut val: u64, w: &mut Writer<'_>) -> Result<()> {{\n"
    ));
    out.push_str(&format!("    for _ in 0..{max_bytes} {{\n"));
    out.push_str(&format!(
        "        let mut byte = (val & 0x{value_mask:02x}) as u8;\n"
    ));
    out.push_str(&format!("        val >>= {value_bits};\n"));
    out.push_str(&format!(
        "        if val != 0 {{ byte |= 0x{cont_mask:02x}; }}\n"
    ));
    out.push_str("        w.write_u8(byte)?;\n");
    out.push_str("        if val == 0 { return Ok(()); }\n");
    out.push_str("    }\n");
    out.push_str("    Err(Error::Overflow)\n");
    out.push_str("}\n\n");

    // ── wire_size ──
    out.push_str(&format!("pub fn {snake}_wire_size(val: u64) -> usize {{\n"));
    out.push_str("    let mut v = val;\n");
    out.push_str("    let mut n = 1usize;\n");
    out.push_str(&format!(
        "    while v >= (1u64 << {value_bits}) && n < {max_bytes} {{\n"
    ));
    out.push_str(&format!("        v >>= {value_bits};\n"));
    out.push_str("        n += 1;\n");
    out.push_str("    }\n");
    out.push_str("    n\n");
    out.push_str("}\n\n");
}

// ── State Machines ──

fn emit_state_machine(out: &mut String, sm: &SemanticStateMachine) {
    let sm_name = to_pascal_case(&sm.name);

    // ── State enum ──
    out.push_str("#[derive(Debug, Clone, PartialEq)]\n");
    out.push_str(&format!("pub enum {sm_name} {{\n"));
    for state in &sm.states {
        let state_name = to_pascal_case(&state.name);
        if state.fields.is_empty() {
            out.push_str(&format!("    {state_name},\n"));
        } else {
            out.push_str(&format!("    {state_name} {{\n"));
            for field in &state.fields {
                let ty = semantic_type_to_rust(&field.ty);
                out.push_str(&format!("        {}: {ty},\n", field.name));
            }
            out.push_str("    },\n");
        }
    }
    out.push_str("}\n\n");

    // ── Event enum ──
    let has_events = !sm.events.is_empty();
    if has_events {
        out.push_str("#[derive(Debug, Clone, PartialEq)]\n");
        out.push_str(&format!("pub enum {sm_name}Event {{\n"));
        for event in &sm.events {
            let event_name = to_pascal_case(&event.name);
            if event.params.is_empty() {
                out.push_str(&format!("    {event_name},\n"));
            } else {
                out.push_str(&format!("    {event_name} {{\n"));
                for param in &event.params {
                    let ty = semantic_type_to_rust(&param.ty);
                    out.push_str(&format!("        {}: {ty},\n", param.name));
                }
                out.push_str("    },\n");
            }
        }
        out.push_str("}\n\n");
    }

    // ── impl block ──
    out.push_str(&format!("impl {sm_name} {{\n"));

    // ── new() constructor ──
    // Find the initial state
    if let Some(initial_state) = sm.states.iter().find(|s| s.state_id == sm.initial_state_id) {
        let initial_name = to_pascal_case(&initial_state.name);
        out.push_str("    pub fn new() -> Self {\n");
        if initial_state.fields.is_empty() {
            out.push_str(&format!("        Self::{initial_name}\n"));
        } else {
            out.push_str(&format!("        Self::{initial_name} {{\n"));
            for field in &initial_state.fields {
                let default_val = if let Some(ref lit) = field.default_value {
                    semantic_literal_to_rust(lit)
                } else {
                    // Use Default::default() for the type
                    "0".into()
                };
                out.push_str(&format!("            {}: {default_val},\n", field.name));
            }
            out.push_str("        }\n");
        }
        out.push_str("    }\n\n");
    }

    // ── dispatch() ──
    if has_events && !sm.transitions.is_empty() {
        out.push_str(&format!(
            "    pub fn dispatch(&mut self, event: &{sm_name}Event) -> Result<()> {{\n"
        ));
        out.push_str("        match (&*self, event) {\n");

        for trans in &sm.transitions {
            let src_state_name = to_pascal_case(&trans.src_state_name);
            let dst_state_name = to_pascal_case(&trans.dst_state_name);
            let event_name = to_pascal_case(&trans.event_name);

            // Find source and destination state definitions
            let src_state = sm.states.iter().find(|s| s.state_id == trans.src_state_id);
            let dst_state = sm.states.iter().find(|s| s.state_id == trans.dst_state_id);
            let event_def = sm.events.iter().find(|e| e.event_id == trans.event_id);

            // Build the match pattern for source state
            let src_pattern = if let Some(src) = src_state {
                if src.fields.is_empty() {
                    format!("Self::{src_state_name}")
                } else {
                    let field_bindings: Vec<String> =
                        src.fields.iter().map(|f| f.name.clone()).collect();
                    format!("Self::{src_state_name} {{ {} }}", field_bindings.join(", "))
                }
            } else {
                format!("Self::{src_state_name}")
            };

            // Build the match pattern for event
            let event_pattern = if let Some(ev) = event_def {
                if ev.params.is_empty() {
                    format!("{sm_name}Event::{event_name}")
                } else {
                    let param_bindings: Vec<String> =
                        ev.params.iter().map(|p| p.name.clone()).collect();
                    format!(
                        "{sm_name}Event::{event_name} {{ {} }}",
                        param_bindings.join(", ")
                    )
                }
            } else {
                format!("{sm_name}Event::{event_name}")
            };

            out.push_str(&format!(
                "            ({src_pattern}, {event_pattern}) => {{\n"
            ));

            // Guard check
            if let Some(ref guard) = trans.guard {
                let guard_str = sm_expr_to_rust_ctx(guard, &sm.states);
                out.push_str(&format!(
                    "                if !({guard_str}) {{ return Err(Error::InvalidState); }}\n"
                ));
            }

            if let Some(ref delegate) = trans.delegate {
                // Delegate: auto-copy src -> dst, then forward event to child SM
                // Try to extract the child field name from the delegate target
                let child_field = extract_delegate_child_field(&delegate.target);
                let child_sm_name = child_field.as_ref().and_then(|fname| {
                    src_state.and_then(|s| {
                        s.fields
                            .iter()
                            .find(|f| f.name == *fname)
                            .and_then(|f| f.child_sm_name.clone())
                    })
                });

                out.push_str("                // delegate: auto-copy + forward to child SM\n");
                out.push_str("                let mut new_state = self.clone();\n");

                if let (Some(field_name), Some(child_sm)) = (&child_field, &child_sm_name) {
                    let child_sm_pascal = to_pascal_case(child_sm);
                    // Extract the event argument name from delegate event
                    let event_param_name = extract_delegate_event_param(&delegate.target);
                    out.push_str(&format!(
                        "                if let Self::{src_state_name} {{ ref mut {field_name}, .. }} = new_state {{\n"
                    ));
                    out.push_str(&format!(
                        "                    let _old = std::mem::discriminant(&*{field_name});\n"
                    ));
                    // We'd need to map the event parameter to the child's event type.
                    // Since that mapping is complex, emit a dispatch call with a comment.
                    if let Some(ref ep) = event_param_name {
                        out.push_str(&format!(
                            "                    // TODO: map *{ep} to {child_sm_pascal}Event variant\n"
                        ));
                        out.push_str(&format!(
                            "                    // {field_name}.dispatch(&{child_sm_pascal}Event::...)?;\n"
                        ));
                    } else {
                        out.push_str(&format!(
                            "                    // TODO: dispatch to {field_name}: {child_sm_pascal}\n"
                        ));
                    }
                    if sm.has_child_state_changed {
                        out.push_str(&format!(
                            "                    if std::mem::discriminant(&*{field_name}) != _old {{\n"
                        ));
                        out.push_str(&format!(
                            "                        let _ = self.dispatch(&{sm_name}Event::ChildStateChanged);\n"
                        ));
                        out.push_str("                    }\n");
                    }
                    out.push_str("                }\n");
                } else {
                    out.push_str("                // TODO: dispatch to child SM field\n");
                }

                out.push_str("                *self = new_state;\n");
                out.push_str("                Ok(())\n");
            } else {
                // Build destination state
                if let Some(dst) = dst_state {
                    if dst.fields.is_empty() {
                        out.push_str(&format!(
                            "                *self = Self::{dst_state_name};\n"
                        ));
                    } else {
                        out.push_str(&format!(
                            "                *self = Self::{dst_state_name} {{\n"
                        ));

                        // For each destination field, check if there's an action that assigns it
                        for dst_field in &dst.fields {
                            let assigned_value =
                                find_action_for_field(&trans.actions, &dst_field.name, &sm.states);
                            if let Some(expr_str) = assigned_value {
                                out.push_str(&format!(
                                    "                    {}: {expr_str},\n",
                                    dst_field.name
                                ));
                            } else {
                                // Try to copy from source state if same field name exists
                                let src_has_field = src_state
                                    .map(|s| s.fields.iter().any(|f| f.name == dst_field.name))
                                    .unwrap_or(false);
                                if src_has_field {
                                    out.push_str(&format!(
                                        "                    {}: *{},\n",
                                        dst_field.name, dst_field.name
                                    ));
                                } else if let Some(ref lit) = dst_field.default_value {
                                    let val = semantic_literal_to_rust(lit);
                                    out.push_str(&format!(
                                        "                    {}: {val},\n",
                                        dst_field.name
                                    ));
                                } else {
                                    out.push_str(&format!(
                                        "                    {}: 0,\n",
                                        dst_field.name
                                    ));
                                }
                            }
                        }

                        out.push_str("                };\n");
                    }
                } else {
                    out.push_str(&format!(
                        "                *self = Self::{dst_state_name};\n"
                    ));
                }

                out.push_str("                Ok(())\n");
            }
            out.push_str("            }\n");
        }

        out.push_str("            _ => Err(Error::InvalidState),\n");
        out.push_str("        }\n");
        out.push_str("    }\n");
    }

    out.push_str("}\n\n");
}

/// Convert a SemanticExpr from the state machine context to Rust code.
/// In SM context, TransitionPeerRef is used for src/dst/event-param fields.
#[allow(dead_code)]
fn sm_expr_to_rust(expr: &SemanticExpr) -> String {
    sm_expr_to_rust_ctx(expr, &[])
}

/// Convert a SemanticExpr with access to SM state definitions for InState/All lookups.
fn sm_expr_to_rust_ctx(expr: &SemanticExpr, sm_states: &[SemanticState]) -> String {
    match expr {
        SemanticExpr::Literal { value } => match value {
            SemanticLiteral::Int(n) => {
                if *n < 0 {
                    format!("({n})")
                } else {
                    format!("{n}")
                }
            }
            SemanticLiteral::Bool(b) => format!("{b}"),
            SemanticLiteral::String(s) => format!("{s:?}"),
            SemanticLiteral::Null => "0".into(),
        },
        SemanticExpr::TransitionPeerRef { reference } => {
            // src.field -> *field (from match binding)
            // dst.field -> field (target assignment)
            // event_param -> *param_name (from match binding)
            if reference.path.is_empty() {
                "()".into()
            } else {
                let field_name = &reference.path[reference.path.len() - 1];
                match reference.peer {
                    TransitionPeerKind::Src => format!("*{field_name}"),
                    TransitionPeerKind::Dst => field_name.clone(),
                    TransitionPeerKind::EventParam => format!("*{field_name}"),
                }
            }
        }
        SemanticExpr::ValueRef { reference } => reference.value_id.clone(),
        SemanticExpr::Binary { op, left, right } => {
            let l = sm_expr_to_rust_ctx(left, sm_states);
            let r = sm_expr_to_rust_ctx(right, sm_states);
            let rust_op = match op.as_str() {
                "and" => "&&",
                "or" => "||",
                o => o,
            };
            format!("({l} {rust_op} {r})")
        }
        SemanticExpr::Unary { op, operand } => {
            let o = sm_expr_to_rust_ctx(operand, sm_states);
            format!("({op}{o})")
        }
        SemanticExpr::Subscript { base, index } => {
            let b = sm_expr_to_rust_ctx(base, sm_states);
            let i = sm_expr_to_rust_ctx(index, sm_states);
            format!("{b}[{i}]")
        }
        SemanticExpr::Coalesce { expr, default } => {
            let e = sm_expr_to_rust_ctx(expr, sm_states);
            let d = sm_expr_to_rust_ctx(default, sm_states);
            // Rust doesn't have ??, use unwrap_or pattern
            format!("{e}.unwrap_or({d})")
        }
        SemanticExpr::InState {
            expr,
            state_id,
            sm_name,
            state_name,
            ..
        } => {
            let expr_rs = sm_expr_to_rust_ctx(expr, sm_states);
            let sm_pascal = to_pascal_case(sm_name);
            let state_pascal = to_pascal_case(state_name);
            // Look up whether this state has fields to emit correct match pattern
            let has_fields = sm_states
                .iter()
                .find(|s| s.state_id == *state_id)
                .map(|s| !s.fields.is_empty())
                .unwrap_or(true); // default to true (use { .. }) if state not found
            if has_fields {
                format!("matches!({expr_rs}, {sm_pascal}::{state_pascal} {{ .. }})")
            } else {
                format!("matches!({expr_rs}, {sm_pascal}::{state_pascal})")
            }
        }
        SemanticExpr::StateConstructor {
            sm_name,
            state_id,
            state_name,
            args,
            ..
        } => {
            let sm_pascal = to_pascal_case(sm_name);
            let state_pascal = to_pascal_case(state_name);
            if args.is_empty() {
                format!("{sm_pascal}::{state_pascal}")
            } else {
                // Try to look up field names from state definitions
                let field_names: Option<Vec<String>> = sm_states
                    .iter()
                    .find(|s| s.state_id == *state_id)
                    .map(|s| s.fields.iter().map(|f| f.name.clone()).collect());

                let arg_strs: Vec<String> = args
                    .iter()
                    .map(|a| sm_expr_to_rust_ctx(a, sm_states))
                    .collect();

                if let Some(names) = field_names {
                    // Pair field names with arg values
                    let fields: Vec<String> = names
                        .iter()
                        .zip(arg_strs.iter())
                        .map(|(name, val)| format!("{name}: {val}"))
                        .collect();
                    format!("{sm_pascal}::{state_pascal} {{ {} }}", fields.join(", "))
                } else {
                    // Fallback: emit positional args as comment
                    format!(
                        "{sm_pascal}::{state_pascal} {{ /* args: {} */ }}",
                        arg_strs.join(", ")
                    )
                }
            }
        }
        SemanticExpr::Fill { value, count } => {
            let val_rs = sm_expr_to_rust_ctx(value, sm_states);
            let cnt_rs = sm_expr_to_rust_ctx(count, sm_states);
            // In Rust, array initialization with a repeated value: [val; count]
            // This works when count is a const and val is Copy.
            format!("[{val_rs}; {cnt_rs}]")
        }
        SemanticExpr::Slice { base, start, end } => {
            let b = sm_expr_to_rust_ctx(base, sm_states);
            let s = sm_expr_to_rust_ctx(start, sm_states);
            let e = sm_expr_to_rust_ctx(end, sm_states);
            format!("{b}[{s}..{e}]")
        }
        SemanticExpr::All {
            collection,
            state_id,
            sm_name,
            state_name,
            ..
        } => {
            let sm_pascal = to_pascal_case(sm_name);
            let state_pascal = to_pascal_case(state_name);
            // Check whether the target state has fields for correct match pattern
            let has_fields = sm_states
                .iter()
                .find(|s| s.state_id == *state_id)
                .map(|s| !s.fields.is_empty())
                .unwrap_or(true);
            let pattern = if has_fields {
                format!("{sm_pascal}::{state_pascal} {{ .. }}")
            } else {
                format!("{sm_pascal}::{state_pascal}")
            };
            // collection is typically a Slice { base, start, end }
            match collection.as_ref() {
                SemanticExpr::Slice { base, start, end } => {
                    let base_rs = sm_expr_to_rust_ctx(base, sm_states);
                    let start_rs = sm_expr_to_rust_ctx(start, sm_states);
                    let end_rs = sm_expr_to_rust_ctx(end, sm_states);
                    format!("({start_rs}..{end_rs}).all(|_ai| matches!({base_rs}[_ai], {pattern}))")
                }
                _ => {
                    let coll_rs = sm_expr_to_rust_ctx(collection, sm_states);
                    format!("{coll_rs}.iter().all(|_ai| matches!(_ai, {pattern}))")
                }
            }
        }
    }
}

/// Find an action that assigns to the given field name in the destination state.
/// Returns the Rust expression string for the assigned value.
fn find_action_for_field(
    actions: &[SemanticAction],
    field_name: &str,
    sm_states: &[SemanticState],
) -> Option<String> {
    for action in actions {
        // Check if the target is the destination field with matching name
        if let SemanticExpr::TransitionPeerRef { reference } = &action.target {
            if reference.peer == TransitionPeerKind::Dst
                && !reference.path.is_empty()
                && reference.path[reference.path.len() - 1] == field_name
            {
                let value_str = sm_expr_to_rust_ctx(&action.value, sm_states);
                return match action.op.as_str() {
                    "=" => Some(value_str),
                    "+=" => Some(format!("(*{field_name} + {value_str})")),
                    "-=" => Some(format!("(*{field_name} - {value_str})")),
                    "*=" => Some(format!("(*{field_name} * {value_str})")),
                    "/=" => Some(format!("(*{field_name} / {value_str})")),
                    _ => Some(value_str),
                };
            }
        }
    }
    None
}

/// Extract the child field name from a delegate target expression.
/// Delegate target is typically `TransitionPeerRef { peer: Src, path: ["child_field"] }`
/// or a `Subscript` over such a ref (e.g., `src.paths[id]`).
fn extract_delegate_child_field(target: &SemanticExpr) -> Option<String> {
    match target {
        SemanticExpr::TransitionPeerRef { reference } => {
            if reference.peer == TransitionPeerKind::Src && !reference.path.is_empty() {
                Some(reference.path[0].clone())
            } else {
                None
            }
        }
        SemanticExpr::Subscript { base, .. } => extract_delegate_child_field(base),
        _ => None,
    }
}

/// Extract the event parameter name from a delegate target expression's context.
/// The delegate's event_name tells us which event is being forwarded.
fn extract_delegate_event_param(target: &SemanticExpr) -> Option<String> {
    // Walk down through Subscript to find the innermost TransitionPeerRef
    match target {
        SemanticExpr::TransitionPeerRef { reference } => {
            if reference.peer == TransitionPeerKind::Src && reference.path.len() > 1 {
                Some(reference.path.last().unwrap().clone())
            } else {
                None
            }
        }
        SemanticExpr::Subscript { base, .. } => extract_delegate_event_param(base),
        _ => None,
    }
}
